name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update hogehoge.txt
      run: |
        echo date > hogehoge.txt
        git config --global user.email "ci-master@example.com"
        git config --global user.name "CI Master"
        git add .
        git commit -m "update hoge.txt"
        git push
        echo finish!
