name: CI

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update hogehoge.txt
      run: |
        git switch master
        echo `date` > hogehoge.txt
        git config --global user.email "ci-master@example.com"
        git config --global user.name "CI Master"
        git add .
        git commit -m "update hogehoge.txt"
        git push
        echo finish!
